fix examples ci (#18)
* fix ci

* exit after 15sec when server doesnt start

* ci exit log fix

* kill zig instead

* pkill example instead

* use kill again

* start bin instead of using run

* better log

* try pid again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,26 +27,42 @@ jobs:
       - name: Check examples
         run: |
           ROOT_DIR=$(pwd)
-          for example_dir in examples/{hello,hello_app,blog,todos_orm_sqlite}/; do
-            echo "Testing $example_dir"
-            cd "$ROOT_DIR/$example_dir"
-            zig build
-            zig build run &
-            SERVER_PID=$!
-            sleep 3
+          for example in {hello,hello_app,blog,todos_orm_sqlite}; do
+              EXAMPLE_DIR="$ROOT_DIR/examples/$example/"
+              echo "Testing $example"
+              cd "$EXAMPLE_DIR"
 
-            URL=http://127.0.0.1:8080
-            if [[ "$example_dir" == "examples/todos_orm_sqlite/" ]]; then
-                URL="http://127.0.0.1:8080/todo"
-            fi
-            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL || echo "failed")
-            kill -TERM $SERVER_PID 2>/dev/null || true
-            
-            # Check the result
-            if [[ "$HTTP_STATUS" == "200" ]]; then
-              echo "$example_dir: OK"
-            else
-              echo "$example_dir: Failed with status $HTTP_STATUS"
-              exit 1
-            fi
+              zig build
+              ./zig-out/bin/$example &
+              SERVER_PID=$!
+              
+              timeout=15
+              while ! nc -z 127.0.0.1 8080; do
+                  echo "Waiting for server..."
+                  sleep 1
+                  timeout=$((timeout - 1))
+                  if [ $timeout -le 0 ]; then
+                      echo "$EXAMPLE_DIR did not start within 15 seconds."
+                      exit 1
+                  fi
+              done
+
+              URL="http://127.0.0.1:8080"
+              if [[ "$example" == "todos_orm_sqlite" ]]; then
+                  URL="http://127.0.0.1:8080/todo"
+              fi
+              echo "GET $URL"
+              HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL || echo "failed")
+
+              echo "Killing process for $example..."
+              kill -TERM $SERVER_PID 2>/dev/null || true
+
+              # Check the result
+              if [[ "$HTTP_STATUS" == "200" ]]; then
+                  echo "$example: OK"
+              else
+                  echo "$example: Failed with status $HTTP_STATUS"
+                  exit 1
+              fi
           done
+
